### ISSUE TITLE
license/copyright

### ISSUE THREAD

**Issue by dmitry-mukhin** [AstinCHOI/Akamai-AuthToken-Python#2]
Want to make sure I understand the terms of using this code.
In the readme it's stated that "(This is Akamai unofficial code)" but later under License section there's: "Copyright 2017 Akamai Technologies, Inc. All rights reserved."

Which is true? :)

**Comment by AstinCHOI** [comment]
Hi @dmitry-mukhin,
I just removed the copyright things. The unofficial code is true.

Thanks,
